package unitinfo.enums;

public enum UnitRank {

    AIRMAN_BASIC,
    AIRMAN,
    AIRMAN_FIRST_CLASS,
    SENIOR_AIRMAN,

    CORPORAL_IN_TRAINING,
    TECHNICAL_SERGEANT,
    MASTER_SERGEANT,
    CHIEF_MASTER_SERGEANT,
    SERGEANT_MAJOR,

    FIRST_LIEUTENANT,
    CAPTAIN,
    MAJOR,
    MAJOR_GENERAL,

    LIEUTENANT_GENERAL,
    GENERAL,
    GENERAL_OF_THE_AIR_FORCE

}
